name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot app
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t sport-app-backend .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag sport-app-backend <your-dockerhub-username>/sport-app-backend:latest
          docker push <your-dockerhub-username>/sport-app-backend:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f infra/kubernetes/deployment.yaml
          kubectl apply -f infra/kubernetes/service.yaml
