parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Cache services
    App\Service\CacheService:
        arguments:
            $venueCache: '@cache.venue'
            $userCache: '@cache.user'
            $sportCache: '@cache.sport'
            $reviewCache: '@cache.review'
            $bookingCache: '@cache.booking'

    # Cache pools
    cache.venue:
        parent: 'cache.app'
        tags: ['cache.pool']

    cache.user:
        parent: 'cache.app'
        tags: ['cache.pool']

    cache.sport:
        parent: 'cache.app'
        tags: ['cache.pool']

    cache.review:
        parent: 'cache.app'
        tags: ['cache.pool']

    cache.booking:
        parent: 'cache.app'
        tags: ['cache.pool']

    # Configure the exception listener
    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception } 