version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: sport-db
    restart: always
    environment:
      POSTGRES_USER: sport_user
      POSTGRES_PASSWORD: sport_pass
      POSTGRES_DB: sport_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: sport-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sport_db
      SPRING_DATASOURCE_USERNAME: sport_user
      SPRING_DATASOURCE_PASSWORD: sport_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: prod
      SERVER_SERVLET_CONTEXT_PATH: /
      CORS_ALLOWED_ORIGINS: "*"
    command: ["java", "-jar", "app.jar"]

  frontend-web:
    build: ./frontend-web
    container_name: sport-frontend-web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api
      - NODE_ENV=development

  frontend-mobile:
    build: ./frontend-mobile
    container_name: sport-frontend-mobile
    restart: always
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend

  frontend-desktop:
    build: ./frontend-desktop
    container_name: sport-frontend-desktop
    restart: always
    ports:
      - "1420:1420"
    depends_on:
      - backend

volumes:
  postgres_data: