version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: sport-db
    restart: always
    environment:
      POSTGRES_USER: sport_user
      POSTGRES_PASSWORD: sport_pass
      POSTGRES_DB: sport_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/docker/php
      dockerfile: Dockerfile
    container_name: sport-backend
    restart: always
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://sport_user:sport_pass@postgres:5432/sport_db?serverVersion=15&charset=utf8
      APP_ENV: prod
      CORS_ALLOW_ORIGIN: '*'

  backend-web:
    image: nginx:alpine
    container_name: sport-backend-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  frontend-web:
    build: ./frontend-web
    container_name: sport-frontend-web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend-web
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
      - NODE_ENV=development

  frontend-mobile:
    build: ./frontend-mobile
    container_name: sport-frontend-mobile
    restart: always
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend-web

  frontend-desktop:
    build: ./frontend-desktop
    container_name: sport-frontend-desktop
    restart: always
    ports:
      - "1420:1420"
    depends_on:
      - backend-web

volumes:
  postgres_data: