version: "3.8"

services:
  database:
    image: postgres:15
    container_name: sport-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sport_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sport_pass}
      POSTGRES_DB: ${POSTGRES_DB:-sport_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sport_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    container_name: sport-backend
    restart: always
    ports:
      - "8080:3000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://sport_user:sport_pass@database:5432/sport_db

  frontend-web:
    build: ./frontend-web
    container_name: sport-frontend-web
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
      - BACKEND_API_URL=http://localhost:8080/api
      - NODE_ENV=development

  frontend-mobile:
    build: ./frontend-mobile
    container_name: sport-frontend-mobile
    restart: always
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"

  frontend-desktop:
    build: ./frontend-desktop
    container_name: sport-frontend-desktop
    restart: always
    ports:
      - "1420:1420"

volumes:
  postgres_data:
