version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://sportapp:sportapp123@db:5432/sport_app_dev
      - JWT_SECRET=dev-secret-key
      - JWT_EXPIRES_IN=7d
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    command: npm run dev

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=sport_app_dev
      - POSTGRES_USER=sportapp
      - POSTGRES_PASSWORD=sportapp123
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=sport_app_test
      - POSTGRES_USER=sportapp
      - POSTGRES_PASSWORD=sportapp123
    ports:
      - "5433:5432"

volumes:
  postgres_dev_data: