api_platform:
    title: 'Sport App API'
    description: 'API for managing sports venues in Sport App'
    version: '1.0.0'
    show_webby: false

    # Enable the Swagger documentation and export
    swagger:
        api_keys:
            # JWT (if needed later)
            #apiKey:
            #    name: Authorization
            #    type: header

    # Enable the GraphQL entrypoint if needed
    # graphql:
    #   enabled: true

    # Default pagination config
    defaults:
        pagination_enabled: true
        pagination_client_enabled: true
        pagination_items_per_page: 10

    # Exception handling
    exception_to_status:
        App\Exception\ResourceNotFoundException: 404
        Symfony\Component\Validator\Exception\ValidationFailedException: 400
        
    # Formats
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html'] 