framework:
    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaced cache keys.
        prefix_seed: sport_app

        # The app cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:
        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost
        app: cache.adapter.filesystem

        # The system cache is used to store things like annotations
        # and translation files. It's not meant to be used for
        # storing data that should persist between deploys.
        system: cache.adapter.system

        # The directory where cache files are stored
        directory: '%kernel.cache_dir%/pools'

        # Enable cache pools with tagging
        pools:
            cache.venue:
                adapter: cache.adapter.filesystem
                tags: true
                default_lifetime: 3600
            cache.user:
                adapter: cache.adapter.filesystem
                tags: true
                default_lifetime: 3600
            cache.sport:
                adapter: cache.adapter.filesystem
                tags: true
                default_lifetime: 3600
            cache.review:
                adapter: cache.adapter.filesystem
                tags: true
                default_lifetime: 3600
            cache.booking:
                adapter: cache.adapter.filesystem
                tags: true
                default_lifetime: 3600
