# .github/workflows/deploy.yml
name: CI/CD Deploy to K3s
on:
  push:
    branches:
      - main
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sport-backend:${{ env.IMAGE_TAG }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sport-frontend:${{ env.IMAGE_TAG }}

      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig && export KUBECONFIG=$(pwd)/kubeconfig

      - name: Deploy via Helm
        run: |
          helm upgrade --install sport-app ./charts/sport-app \
            -f charts/sport-app/values.yaml \
            -f charts/sport-app/values-${{ github.ref_name }}.yaml \
            --set backend.image=ghcr.io/${{ github.repository_owner }}/sport-backend:${{ env.IMAGE_TAG }} \
            --set frontend.image=ghcr.io/${{ github.repository_owner }}/sport-frontend:${{ env.IMAGE_TAG }}